// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoFG_02Y8DfYIGeCl7NytnIyQpkoF_EBo',
    appId: '1:664793252514:android:7966df1eb0ee37c5bf4dfb',
    messagingSenderId: '664793252514',
    projectId: 'safebrowser-f49bf',
    storageBucket: 'safebrowser-f49bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoFG_02Y8DfYIGeCl7NytnIyQpkoF_EBo',
    appId: '1:664793252514:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '664793252514',
    projectId: 'safebrowser-f49bf',
    storageBucket: 'safebrowser-f49bf.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoFG_02Y8DfYIGeCl7NytnIyQpkoF_EBo',
    appId: '1:664793252514:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '664793252514',
    projectId: 'safebrowser-f49bf',
    storageBucket: 'safebrowser-f49bf.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoFG_02Y8DfYIGeCl7NytnIyQpkoF_EBo',
    appId: '1:664793252514:web:YOUR_WEB_APP_ID',
    messagingSenderId: '664793252514',
    projectId: 'safebrowser-f49bf',
    storageBucket: 'safebrowser-f49bf.firebasestorage.app',
  );
}
